83 create teensy like stm dev board
Terrapin-Rocket-Team/SRAD-Avionics pull request #144
Opened 2024-09-23 00:09 UTC by dshi0322

Component's datasheets are uploaded so any considerations i missed feel free to tell me or if there are any general issues as well.

2024-09-24 01:59 UTC, dshi0322 commented
sorry I messed up some files i think and im trying to fix it soon

2024-09-24 04:10 UTC, varun-un commented
files & folders should be fixed

2024-09-25 19:56 UTC, varun-un requested changes
You should move your decoupling capacitors to be as close as possible to the pads and lines they're connecting

Also, if you could label the row of breakout pins you got on the board that be good. If you could break a few of them out into sets of four or so pins for things like I2C and SPI and so, so that way we can easier use JSTs to connect them instead of just header pins

2024-10-23 05:16 UTC, varun-un commented
Set of changes from PDR review:

- Decoupling caps closer
- Terminal Resistors
- 4+ layers, with top and bottom ground copper layers and middle signal layers (where realistic, like for high frequency lines)
- Reduce viases where possible
- Avoid circularly connecting traces (EMF interference or something since you circulate current)

2025-05-02 04:32 UTC, closed without merging