BMI088 Accelerometer and Gyroscope Implementation
Terrapin-Rocket-Team/SRAD-Avionics pull request #153
Opened 2024-09-26 20:58 UTC by rk234

Closes #145 

* Added basic implementation of BMI088 sensor implementation
* Added dependency on [BMI088 library](https://github.com/bolderflight/bmi088-arduino/blob/main/README.md)

Magnetometer methods currently return default value of Vector<3>(0, 0, 0) pending a decision on restructuring IMU code.

2024-09-27 04:09 UTC, DrewBrandt requested changes
Do you mind adding the .idea folder to .gitignore? They appear to be local IDE configuration files. After you add them, you can `git rm` them to remove the currently tracked versions

Everything else seems fine. Thanks.

2024-09-27 04:09 UTC, DrewBrandt commented on Spaceport/Code/Teensy-Based Avionics/platformio.ini
> +build_src_filter = +<*> -<StateTest/*> +<StateTest/TestUtils.h> -<GroundStationReceiver/*> +<Sensors/*>
Was it not properly building without this? If not, then something is wrong because I think it should have

2024-09-27 04:12 UTC, DrewBrandt commented
Also a note that as you know, we are working on the IMU in MMFS right now, so these variables will need to be revisited once we update to whatever new version we release

2024-09-27 13:11 UTC, rk234 commented on Spaceport/Code/Teensy-Based Avionics/platformio.ini
> +build_src_filter = +<*> -<StateTest/*> +<StateTest/TestUtils.h> -<GroundStationReceiver/*> +<Sensors/*>
You're right, it's building without it.

2024-09-27 13:17 UTC, rk234 commented
Issues should be fixed now

2024-09-28 02:35 UTC, DrewBrandt approved these changes

2024-09-28 02:35 UTC, DrewBrandt commented on Spaceport/Code/Teensy-Based Avionics/src/Sensors/BMI088.cpp
> +    measuredGyro = mmfs::Vector<3>(gyro.getGyroX_rads(), gyro.getGyroY_rads(), gyro.getGyroZ_rads());
This will end up changing when we upgrade to mmfs 2.1, but we dk when that will be so for now this works

2024-09-30 06:37 UTC, varun-un commented on Spaceport/Code/Teensy-Based Avionics/src/Sensors/BMI088.cpp
> +    measuredGyro = mmfs::Vector<3>(gyro.getGyroX_rads(), gyro.getGyroY_rads(), gyro.getGyroZ_rads());
should we merge this in now and then later update to mmfs 2.1, or should we not merge this branch and just handle that here?

2024-09-30 14:38 UTC, DrewBrandt commented on Spaceport/Code/Teensy-Based Avionics/src/Sensors/BMI088.cpp
> +    measuredGyro = mmfs::Vector<3>(gyro.getGyroX_rads(), gyro.getGyroY_rads(), gyro.getGyroZ_rads());
Up to you. Michael wants Ezra to review the IMU changes, which he said would happen before the hardware came in. It might be worth it to just wait until that's ready. The only thing that should change is which variables the sensor read results are stored in. there shouldn't be any other changes.

2024-10-04 09:34 UTC, merged