did read and init for MS5611
Terrapin-Rocket-Team/SRAD-Avionics pull request #154
Opened 2024-09-30 23:43 UTC by Azhanzz

2024-09-30 23:46 UTC, Azhanzz commented
Used this library: https://www.arduino.cc/reference/en/libraries/ms5611/

2024-10-01 17:05 UTC, DrewBrandt requested changes
Looks good. Only minor changes. Was it hard to implement? How was working with MMFS (even for just this small thing?)

2024-10-01 17:05 UTC, DrewBrandt commented on Spaceport/Code/Teensy-Based Avionics/src/Sensors/MS5611.cpp
> +       return true;
can you set `initialized = true` in here so that we know the sensor is working before trying to access it in the future?

2024-10-01 17:05 UTC, DrewBrandt commented on Spaceport/Code/Teensy-Based Avionics/src/Sensors/MS5611.h
> +       MS5611(const char *name);
Can you provide a default name, probably something like "MS5611"

2024-10-16 02:39 UTC, DrewBrandt approved these changes

2024-10-16 20:53 UTC, merged